2021-08-30T22:52:45.781004+0100 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (464207), thread 'MainThread' (140335139718976):
Traceback (most recent call last):

> File "/home/mic/python/notes/add_md_page.py", line 17, in <module>
    add_md_page()
    └ <function add_md_page at 0x7fa2511a04c0>

  File "/home/mic/python/notes/add_md_page.py", line 13, in add_md_page
    print(add.tit)
          └ <module 'add' from '/home/mic/python/notes/add.py'>

AttributeError: module 'add' has no attribute 'tit'
2021-08-30T22:53:27.299373+0100 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (464218), thread 'MainThread' (139934953535296):
Traceback (most recent call last):

> File "/home/mic/python/notes/add_md_page.py", line 17, in <module>
    add_md_page()
    └ <function add_md_page at 0x7f45242564c0>

  File "/home/mic/python/notes/add_md_page.py", line 13, in add_md_page
    print(add.titulo)
          └ <module 'add' from '/home/mic/python/notes/add.py'>

AttributeError: module 'add' has no attribute 'titulo'
2021-08-30T22:53:43.283379+0100 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (464244), thread 'MainThread' (139998646310720):
Traceback (most recent call last):

> File "/home/mic/python/notes/add_md_page.py", line 17, in <module>
    add_md_page()
    └ <function add_md_page at 0x7f53f88804c0>

  File "/home/mic/python/notes/add_md_page.py", line 13, in add_md_page
    print(add.titulo())
          └ <module 'add' from '/home/mic/python/notes/add.py'>

AttributeError: module 'add' has no attribute 'titulo'
2021-08-30T22:54:53.645351+0100 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (464303), thread 'MainThread' (139892786030400):
Traceback (most recent call last):

> File "/home/mic/python/notes/add_md_page.py", line 17, in <module>
    add_md_page()
    └ <function add_md_page at 0x7f3b52c454c0>

  File "/home/mic/python/notes/add_md_page.py", line 13, in add_md_page
    print(add.titulo())
          └ <module 'add' from '/home/mic/python/notes/add.py'>

AttributeError: module 'add' has no attribute 'titulo'
2021-08-31T04:51:51.068670+0100 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (479960), thread 'MainThread' (139772756756288):
Traceback (most recent call last):

> File "/home/mic/python/notes/apagar.py", line 37, in <module>
    apagar()
    └ <function apagar at 0x7f1f60841820>

  File "/home/mic/python/notes/apagar.py", line 27, in apagar
    filename = os.path.basename(record)
               │  │    │        └ ('http://localhost/notes/pages/html/uber.html',)
               │  │    └ <function basename at 0x7f1f613dba60>
               │  └ <module 'posixpath' from '/usr/lib/python3.9/posixpath.py'>
               └ <module 'os' from '/usr/lib/python3.9/os.py'>

  File "/usr/lib/python3.9/posixpath.py", line 142, in basename
    p = os.fspath(p)
        │  │      └ ('http://localhost/notes/pages/html/uber.html',)
        │  └ <built-in function fspath>
        └ <module 'os' from '/usr/lib/python3.9/os.py'>

TypeError: expected str, bytes or os.PathLike object, not tuple
2021-08-31T04:53:05.197478+0100 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (479991), thread 'MainThread' (140715504510784):
Traceback (most recent call last):

> File "/home/mic/python/notes/apagar.py", line 39, in <module>
    apagar()
    └ <function apagar at 0x7ffae0a93820>

  File "/home/mic/python/notes/apagar.py", line 29, in apagar
    filename = os.path.basename(record)
               │  │    │        └ ('http://localhost/notes/pages/html/uber.html',)
               │  │    └ <function basename at 0x7ffae162da60>
               │  └ <module 'posixpath' from '/usr/lib/python3.9/posixpath.py'>
               └ <module 'os' from '/usr/lib/python3.9/os.py'>

  File "/usr/lib/python3.9/posixpath.py", line 142, in basename
    p = os.fspath(p)
        │  │      └ ('http://localhost/notes/pages/html/uber.html',)
        │  └ <built-in function fspath>
        └ <module 'os' from '/usr/lib/python3.9/os.py'>

TypeError: expected str, bytes or os.PathLike object, not tuple
2021-08-31T05:00:14.847131+0100 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (480312), thread 'MainThread' (139667936692032):
Traceback (most recent call last):

> File "/home/mic/python/notes/apagar.py", line 42, in <module>
    apagar()
    └ <function apagar at 0x7f06f8c0e820>

  File "/home/mic/python/notes/apagar.py", line 32, in apagar
    cmd = "rm " + record + "; " + "rm " + md_page + "'"
                  │                       └ "/srv/http/notes/pages/markdown/contact.h.md'"
                  └ ('http://localhost/notes/pages/html/contact.html',)

TypeError: can only concatenate str (not "tuple") to str
2021-08-31T07:05:47.445002+0100 - __main__ - ERROR - An error has been caught in function '<module>', process 'MainProcess' (485128), thread 'MainThread' (140336416106304):
Traceback (most recent call last):

> File "/home/mic/python/notes/main.py", line 44, in <module>
    add_md_page()
    └ <function add_md_page at 0x7fa29cc22f70>

  File "/home/mic/python/notes/add.py", line 95, in add_md_page
    print(f"[*] - It was created the markdown file named, {add.md_path}.", fore="#acac87")

TypeError: 'fore' is an invalid keyword argument for print()
